// __TABLE_H__

#ifndef __TABLE_H__
#define __TABLE_H__

#define TABLE_ALIGN_LEFT 1
#define TABLE_ALIGN_CENTER 2
#define TABLE_ALIGN_RIGHT 3

#define TABLE_POSITION_HLINE 1
#define TABLE_POSITION_VLINE 2
#define TABLE_POSITION_TOP_LEFT 3
#define TABLE_POSITION_TOP_CENTER 4
#define TABLE_POSITION_TOP_RIGHT 5
#define TABLE_POSITION_MIDDLE_LEFT 6
#define TABLE_POSITION_MIDDLE_CENTER 7
#define TABLE_POSITION_MIDDLE_RIGHT 8
#define TABLE_POSITION_BOTTOM_LEFT 9
#define TABLE_POSITION_BOTTOM_CENTER 10
#define TABLE_POSITION_BOTTOM_RIGHT 11

#define TABLE_BORDER_SIMPLE 1
#define TABLE_BORDER_SINGLE 2
#define TABLE_BORDER_SINGLE_BOLD 3
#define TABLE_BORDER_DOUBLE 4

#endif //__TABLE_H__
